

 const constant={
   SEQUENCEMODE_SPIN_COST:100,
   SEQUENCEMODE_EARNED_COIN:1000,
   SEQUENCEMODE_NUMBER_RANGE:5,
   MINIMUM_COIN_SEQUENCE:100,
   TOTAL_SEQUENCE:10,
   JACKPOTMODE_SPIN_COST:1000,
   JACKPOTMODE_EARNED_COIN:5000,
   JACKPOTMODE_NUMBER_RANGE:5,
   MINIMUM_COIN_JACKPOT:1000

}
module.exports = constant